import { Separator } from "@/components/ui/separator"
import { Shield, Eye, Server, Globe, Mail } from "lucide-react"

export default function PrivacyPage() {
  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)]">
      {/* Hero Section */}
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-b from-background to-muted">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Privacy Policy</h1>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                How we collect, use, and protect your information
              </p>
              <p className="text-sm text-muted-foreground">Last updated: March 1, 2025</p>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl space-y-12">
            {/* Introduction */}
            <div className="space-y-4">
              <div className="inline-flex items-center rounded-lg bg-muted px-3 py-1 text-sm">
                <Shield className="mr-1 h-4 w-4" />
                <span>Your Privacy Matters</span>
              </div>
              <p className="text-muted-foreground">
                At JobSphere, we take your privacy seriously. This Privacy Policy explains how we collect, use,
                disclose, and safeguard your information when you use our website and services. Please read this privacy
                policy carefully. If you do not agree with the terms of this privacy policy, please do not access the
                site.
              </p>
              <p className="text-muted-foreground">
                We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will
                alert you about any changes by updating the "Last updated" date of this Privacy Policy. You are
                encouraged to periodically review this Privacy Policy to stay informed of updates.
              </p>
            </div>

            <Separator />

            {/* Information We Collect */}
            <div className="space-y-4">
              <div className="flex items-center space-x-2">
                <Eye className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-bold">Information We Collect</h2>
              </div>
              <p className="text-muted-foreground">
                We may collect information about you in a variety of ways. The information we may collect via the Site
                includes:
              </p>
              <div className="space-y-4 pl-6">
                <div>
                  <h3 className="font-bold">Personal Data</h3>
                  <p className="text-muted-foreground">
                    Personally identifiable information, such as your name, email address, and telephone number, that
                    you voluntarily give to us when you register with the Site or when you choose to participate in
                    various activities related to the Site. You are under no obligation to provide us with personal
                    information of any kind, however your refusal to do so may prevent you from using certain features
                    of the Site.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold">Derivative Data</h3>
                  <p className="text-muted-foreground">
                    Information our servers automatically collect when you access the Site, such as your IP address,
                    your browser type, your operating system, your access times, and the pages you have viewed directly
                    before and after accessing the Site.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold">Interview Data</h3>
                  <p className="text-muted-foreground">
                    When you use our mock interview services, we collect your responses, including audio recordings if
                    you enable speech recognition, transcripts of your answers, and performance metrics generated by our
                    AI.
                  </p>
                </div>
              </div>
            </div>

            <Separator />

            {/* Use of Your Information */}
            <div className="space-y-4">
              <div className="flex items-center space-x-2">
                <Server className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-bold">Use of Your Information</h2>
              </div>
              <p className="text-muted-foreground">
                Having accurate information about you permits us to provide you with a smooth, efficient, and customized
                experience. Specifically, we may use information collected about you via the Site to:
              </p>
              <ul className="list-disc pl-10 space-y-2 text-muted-foreground">
                <li>Create and manage your account.</li>
                <li>Deliver targeted interview practice and feedback tailored to your needs.</li>
                <li>Email you regarding your account or order.</li>
                <li>Generate a personal profile about you to make future visits to the Site more personalized.</li>
                <li>Increase the efficiency and operation of the Site.</li>
                <li>Monitor and analyze usage and trends to improve your experience with the Site.</li>
                <li>Notify you of updates to the Site.</li>
                <li>Offer new products, services, and/or recommendations to you.</li>
                <li>Perform other business activities as needed.</li>
                <li>Request feedback and contact you about your use of the Site.</li>
                <li>Resolve disputes and troubleshoot problems.</li>
                <li>Respond to product and customer service requests.</li>
              </ul>
            </div>

            <Separator />

            {/* Disclosure of Your Information */}
            <div className="space-y-4">
              <div className="flex items-center space-x-2">
                <Globe className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-bold">Disclosure of Your Information</h2>
              </div>
              <p className="text-muted-foreground">
                We may share information we have collected about you in certain situations. Your information may be
                disclosed as follows:
              </p>
              <div className="space-y-4 pl-6">
                <div>
                  <h3 className="font-bold">By Law or to Protect Rights</h3>
                  <p className="text-muted-foreground">
                    If we believe the release of information about you is necessary to respond to legal process, to
                    investigate or remedy potential violations of our policies, or to protect the rights, property, and
                    safety of others, we may share your information as permitted or required by any applicable law,
                    rule, or regulation.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold">Third-Party Service Providers</h3>
                  <p className="text-muted-foreground">
                    We may share your information with third parties that perform services for us or on our behalf,
                    including payment processing, data analysis, email delivery, hosting services, customer service, and
                    marketing assistance.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold">Marketing Communications</h3>
                  <p className="text-muted-foreground">
                    With your consent, or with an opportunity for you to withdraw consent, we may share your information
                    with third parties for marketing purposes, as permitted by law.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold">Business Transfers</h3>
                  <p className="text-muted-foreground">
                    If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your information may
                    be transferred as part of that transaction. We will notify you before your information is
                    transferred and becomes subject to a different Privacy Policy.
                  </p>
                </div>
              </div>
            </div>

            <Separator />

            {/* Security of Your Information */}
            <div className="space-y-4">
              <div className="flex items-center space-x-2">
                <Shield className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-bold">Security of Your Information</h2>
              </div>
              <p className="text-muted-foreground">
                We use administrative, technical, and physical security measures to help protect your personal
                information. While we have taken reasonable steps to secure the personal information you provide to us,
                please be aware that despite our efforts, no security measures are perfect or impenetrable, and no
                method of data transmission can be guaranteed against any interception or other type of misuse.
              </p>
            </div>

            <Separator />

            {/* Contact Us */}
            <div className="space-y-4">
              <div className="flex items-center space-x-2">
                <Mail className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-bold">Contact Us</h2>
              </div>
              <p className="text-muted-foreground">
                If you have questions or comments about this Privacy Policy, please contact us at:
              </p>
              <div className="bg-muted p-4 rounded-lg">
                <p className="font-medium">JobSphere, Inc.</p>
                <p className="text-muted-foreground">123 Interview Street</p>
                <p className="text-muted-foreground">San Francisco, CA 94103</p>
                <p className="text-muted-foreground">privacy@jobsphere.com</p>
                <p className="text-muted-foreground">1-800-JOBSPHERE</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

